<a href="https://colab.research.google.com/github/YaashxMishra/aws-python/blob/main/day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Slicing**
# array[start:stop:step]

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4])
print(*arr[0:4])
print(arr[0:6:2])
print(arr[0:6:3])
print(arr[-1])
print(arr[:])
print(arr[::2])# jump by one
print(arr[::-1]) # reverse the list

3
[1 2 3 4]
1 2 3 4
[1 3 5]
[1 4]
5
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


# 2D

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0:2]) # rows
print(arr[:,0]) # all rows and 0th column
print(arr[:,1])
print(arr[0,0])


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
1
40


In [ ]:
ar=np.array([[10,20],[30,40]])
print(ar[1,1])
print(ar[0,0])
print(ar[:,1])

print(ar[[0,1],[1,0]])  # [0,1] = row indices, [1,0] = column indices; selects ar[0,1] and ar[1,0] -> [20, 30]
print(ar[[0,1],[0,1]])  # [0,1] = row indices, [0,1] = column indices; selects ar[0,0] and ar[1,1] -> [10, 40]



40
10
[20 40]
[20 30]
[10 40]


In [ ]:
a=np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],[7526,86,647236],[9528,45,428760],[10788,17,183396]])
print(a)
print(a[[2,3,3,3],[0,0,1,2]])
print(a[0,:2])
print(a[4:,1])
print(a[4:,2])
print(a[[0,1],[2,1]])

[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]
 [  7526     86 647236]
 [  9528     45 428760]
 [ 10788     17 183396]]
[  4100   7526     86 647236]
[2453   75]
[45 17]
[428760 183396]
[183975     99]


# **3D**

In [ ]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr.ndim) # 3D
print('\n')
print(arr[0]) # block
print('\n')
print(arr[0,0]) # block -> row
print('\n')
print(arr[0,0,1]) # block -> row -> cols
print('\n')
print(arr[:,:,:]) # all block -> all rows ->all cols
print('\n')
print(arr[:,0]) # all block -> 0th rows
print('\n')
print(arr[:,:,0]) # all block -> all rows -> 0th cols

3


[[1 2]
 [3 4]]


[1 2]


2


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[1 2]
 [5 6]]


[[1 3]
 [5 7]]


# **For Loop**

In [ ]:
# For 1D
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
for i in arr:
  print(i)

[10 20 30 40]
10
20
30
40


In [ ]:
# For 2D

import numpy as np
arr=np.array([[10,20],[30,40]])
print(arr)
for i in arr:
  print(*i)

for i in arr:
  for j in i:
    print(j)
print('\n')
for i in arr.flat:
  print(i)

[[10 20]
 [30 40]]
10 20
30 40
10
20
30
40


10
20
30
40


In [ ]:
# For 3D

import numpy as np
arr=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr)
for i in arr:      # Iterate over 2D arrays
    for j in i:    # Iterate over 1D arrays (rows)
        for k in j:# Iterate over individual elements
            print(k)
print('\n')
for i in arr.flat:
  print(i)

print('\n')
for i in arr.flatten():
  print(i)

print('\n')
for i in np.nditer(arr):
  print(i)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
10
20
30
40
50
60
70
80


10
20
30
40
50
60
70
80


10
20
30
40
50
60
70
80


10
20
30
40
50
60
70
80


# **Sorting**

In [ ]:
import numpy as np
arr=np.array([10,35,40,7,15,20])
print(arr)
print(np.sort(arr)) #ascending
print(np.sort(arr)[::-1]) #decending

# 2D
arr1=arr.reshape(2,3)
print(arr1)
print(np.sort(arr1)) # default rowise sorting
print(np.sort(arr1,axis=0)) # axis=0 is columnwise sorting
print(np.sort(arr1,axis=1)) # axis=1 is rowise sorting

[10 35 40  7 15 20]
[ 7 10 15 20 35 40]
[40 35 20 15 10  7]
[[10 35 40]
 [ 7 15 20]]
[[10 35 40]
 [ 7 15 20]]
[[ 7 15 20]
 [10 35 40]]
[[10 35 40]
 [ 7 15 20]]


# **Filter**

In [1]:
# 1D
import numpy as np
arr=np.array([10,20,30,40])
print(arr[0:3])
print(arr[arr>20])

[10 20 30]
[30 40]


In [4]:
# Where
import numpy as np
arr=np.array([10,20,30,40])
print(np.where(arr>20,'true','false'))
print(np.where(arr<=20,arr*2,arr))

['false' 'false' 'true' 'true']
[20 40 30 40]
